version: '3.8'

services:
  # ==========================
  # HADOOP MASTER NODE
  # ==========================
  hadoop-master:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - "9870:9870"    # HDFS NameNode UI
      - "8088:8088"    # YARN ResourceManager UI
      - "7077:7077"    # Spark Master
      - "19888:19888"  # JobHistory Server
      - "8080:8080"    # Jupyter Notebook
      - "9000:9000"    # HDFS RPC
    volumes:
      - "C:/Users/user/Documents/hadoop_project:/shared_volume"
    networks:
      - hadoop
    tty: true
    stdin_open: true
    command: sh -c "service ssh start && bash"


  # ==========================
  # HADOOP SLAVE 1
  # ==========================
  hadoop-slave1:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    ports:
      - "8040:8042"    # NodeManager Web UI
    networks:
      - hadoop
    tty: true
    stdin_open: true
    command: sh -c "service ssh start && bash"

  # ==========================
  # HADOOP SLAVE 2
  # ==========================
  hadoop-slave2:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    ports:
      - "8041:8042"    # NodeManager Web UI
    networks:
      - hadoop
    tty: true
    stdin_open: true
    command: sh -c "service ssh start && bash"

# ==========================
# NETWORK
# ==========================
networks:
  hadoop:
    driver: bridge